import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import express from 'express';
import type { AddressInfo } from 'node:net';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { z } from 'zod';
import { config } from '../server/config.js';
import { entityPlan, connectEntityExport } from '../server/mcp.js';
import { Store } from '../server/store.js';
import { addOutcome, command, createMeeting, saveTemplate } from '../server/domain.js';
import type { Template } from '../shared/model.js';
test('risk export uses explicit route and real advertised schema; requires approval, returns draft', async t => {
  const mcp = new McpServer({ name: 'customer-risk', version: '1' }); let writes = 0;
  mcp.tool('create_risk', { tenant_uuid: z.string(), name: z.string(), custom_id: z.string().optional(), data: z.record(z.unknown()).optional() }, async args => { writes++; assert.equal(args.name, 'Lieferausfall'); return { content: [{ type: 'text', text: JSON.stringify({ draft_created: true, draftId: 'draft', entityUuid: 'risk', status: 'draft' }) }] }; });
  const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: () => randomUUID() }); await mcp.connect(transport);
  const app = express(); app.use(express.json()); app.all('/mcp', (req, res) => transport.handleRequest(req, res, req.body));
  const server = app.listen(0, '127.0.0.1'); await new Promise<void>(r => server.once('listening', r));
  const prior = { entityRoutes: config.entityRoutes, mcpToken: config.mcpToken, rolealphaTenant: config.rolealphaTenant };
  config.entityRoutes = { risk: { url: `http://127.0.0.1:${(server.address() as AddressInfo).port}/mcp`, tool: 'create_risk', label: 'Risiko' } }; config.mcpToken = 'customer'; config.rolealphaTenant = 'customer';
  t.after(async () => { Object.assign(config, prior); await mcp.close(); await new Promise<void>(r => server.close(() => r())); });
  const store = new Store(':memory:'); await store.initialize(); await store.seed('customer'); const actor = { id: 'owner', name: 'Owner', tenantId: 'customer', admin: true };
  let template = (await store.list<Template>('customer', 'template'))[0]; const step = template.steps.find(s => s.kind === 'agenda')!; step.outputs = ['risk', 'okr', 'it_system']; template = await saveTemplate(store, actor, template, template.id, template.version);
  const meeting = await createMeeting(store, actor, { templateId: template.id, title: 'Weekly', circle: 'Team' }); addOutcome(meeting, actor, { stepId: step.id, type: 'risk', title: 'Lieferausfall' });
  const output = meeting.outcomes[0]; assert.throws(() => entityPlan(meeting, output), /bestätigte/);
  command(meeting, actor, { type: 'outcome.review', id: output.id, status: 'approved' });
  assert.throws(() => entityPlan(meeting, { ...output, type: 'it_system' }), /kein MCP-Ziel/);
  const plan = entityPlan(meeting, output); const connection = await connectEntityExport(plan); assert.equal(writes, 0);
  const receipt = await connection.send(); assert.equal(receipt.entityUuid, 'risk'); assert.equal(writes, 1); await connection.close(); await store.close();
});
