import { test } from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import { randomUUID } from 'node:crypto';
import type { AddressInfo } from 'node:net';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { z } from 'zod';
import { config } from '../server/config.js';
import { sendMeetingDraft } from '../server/mcp.js';
import { Store } from '../server/store.js';
import { addOutcome, command, createMeeting } from '../server/domain.js';
import type { Template } from '../shared/model.js';

test('MCP adapter calls real Streamable HTTP create_meeting and verifies draft receipt', async t => {
  const app = express(); app.use(express.json()); const calls: unknown[] = [];
  const mcp = new McpServer({ name: 'test-rolealpha', version: '1.0.0' });
  mcp.tool('create_meeting', { tenant_uuid: z.string(), name: z.string(), custom_id: z.string(), data: z.record(z.unknown()) }, async args => { calls.push(args); return { content: [{ type: 'text', text: JSON.stringify({ draft_created: true, draftId: 'draft-1', entityUuid: 'entity-1', status: 'draft' }) }] }; });
  const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: () => randomUUID() }); await mcp.connect(transport);
  app.all('/mcp', async (req, res) => { assert.equal(req.headers.authorization, 'Bearer test-customer-token'); await transport.handleRequest(req, res, req.body); });
  const server = app.listen(0, '127.0.0.1'); await new Promise<void>(r => server.once('listening', r));
  const before = { mcpUrl: config.mcpUrl, mcpToken: config.mcpToken, rolealphaTenant: config.rolealphaTenant };
  config.mcpUrl = `http://127.0.0.1:${(server.address() as AddressInfo).port}/mcp`; config.mcpToken = 'test-customer-token'; config.rolealphaTenant = 'customer';
  t.after(async () => { Object.assign(config, before); await mcp.close(); await new Promise<void>(r => server.close(() => r())); });
  const store = new Store(':memory:'); await store.initialize(); await store.seed('customer');
  const actor = { id: 'owner', name: 'Owner', tenantId: 'customer', admin: true }; const template = (await store.list<Template>('customer', 'template')).find(t => t.category === 'tactical')!;
  const meeting = await createMeeting(store, actor, { title: 'Weekly', circle: 'Product', templateId: template.id }); const step = template.steps.find(s => s.kind === 'agenda')!;
  addOutcome(meeting, actor, { stepId: step.id, title: 'Task', type: 'task' }); command(meeting, actor, { type: 'outcome.review', id: meeting.outcomes[0].id, status: 'approved' });
  const receipt = await sendMeetingDraft(meeting, meeting.outcomes); assert.equal(receipt.draftId, 'draft-1'); assert.equal(calls.length, 1); assert.equal((calls[0] as { tenant_uuid: string }).tenant_uuid, 'customer'); await store.close();
});
